config/routes.rb
# ユーザ登録用のルーティング
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
  # フォロー中のユーザとフォローされているユーザ一覧を表示するページは必要です。そのためのルーティング
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  # create, destroy アクション実装
  resources :microposts, only: [:create, :destroy]
  # ログインユーザがユーザをフォロー/アンフォローできるようにするルーティング設定
  resources :relationships, only: [:create, :destroy]
  # ログインユーザーがお気に入り登録できるようにするルーティング設定　12/10
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # 保存する前に { ○○をする }
  # self.email.downcase! → メールアドレスに、もし大文字（例えば M とか）があれば、これを強制的に小文字（例えば m とか）に変換する
  before_save { self.email.downcase! }
  # nameのバリデーション　カラを許さず５０文字以内
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },

                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  # ユーザモデルに書くことによって、主語が「ユーザー」と特定できます
  # よって、「ユーザーが」「複数の」「マイクロポストを」保持  できるという意味になります
  has_many :microposts
  has_many :relationships
  has_many :favorites
  # user.followingsと書けば、user がフォローしているUser達を取得できるようにする機能を提供する。
  # 中間テーブル(Relationship)から先のモデルを参照してくれるので、 User から直接、多対多の User 達を取得することができる
  has_many :followings, through: :relationships, source: :follow
  # 逆方向
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorited, through: :favorites, source: :micropost
  #　フォローとアンフォローの注意点
  # 自分自身ではないか / 既にフォローしているか
  
  # フォロー機能
  # => フォローしようとしている「other_user」が自分自身ではないかを検証している。
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end  
  
  # アンフォロー機能
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
   # お気に入り追加機能
  def favorite(micropost)
    self.favorites.find_or_create_by(micropost_id: micropost.id)
  end

  # お気に入り解除機能
  def unfavorite(micropost)
    favorite = self.favorites.find_by(micropost_id: micropost.id)
    favorite.destroy if favorite
  end

  def favorite?(micropost)
    self.favorited.include?(micropost)
  end

  # タイムライン用のマイクロポストを取得するためのメソッド
  def feed_microposts
    Micropost.where(user_id: self.following_ids + [self.id]) # Micropost.where(user_id: フォローユーザ + 自分自身) となる Micropost を全て取得し
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # require_user_logged_inは、ログインしていれば何もせず、ログインしていなければログインページに強制的にリダイレクトされる。
  before_action :require_user_logged_in, only: [:index, :show, :followers, :followings, :favorites, :microposts]
    # 全ユーザ一覧が欲しいのでUser.allで取得、ページネーション適用に必要な記述も追加
  def index
    @users = User.all.page(params[:page])
  end

  def show # Micropostsも表示する
    @user = User.find(params[:id])
    @microposts = @user.microposts.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render.new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
    
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)      
  end
  
  def microposts
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page])
    counts(@user)
  end

  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorited.page(params[:page])
    counts(@user)
  end

  private

  def user_params
      # password_confirmationは、パスワードの確認のために使用される
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @favorites %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/microposts.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'favorites/favorite_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'users', users: @microposts %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <!--f.object は @user が代入されています-->
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="form_group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.text_field :password, class: 'form-control' %>
    </div>
    
    <div class="form_group">
      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.text_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <%= f.submit 'Sign up', class: 'btn-primary btn-block' %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--ユーザー詳細ページ => ユーザーの名前とGravatarを表示しているn -->
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified"> <!--Micropostsを表示、Micropostsのカウント数も表示-->
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Micoroposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>Favorites <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @microposts %>
  </div>
</div>